// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: grpc/raw_protos/post_protos/post.proto

package post_protos

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     uint64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID uint64 `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Title  string `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	Body   string `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *PostParams) Reset() {
	*x = PostParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_raw_protos_post_protos_post_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostParams) ProtoMessage() {}

func (x *PostParams) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_raw_protos_post_protos_post_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostParams.ProtoReflect.Descriptor instead.
func (*PostParams) Descriptor() ([]byte, []int) {
	return file_grpc_raw_protos_post_protos_post_proto_rawDescGZIP(), []int{0}
}

func (x *PostParams) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *PostParams) GetUserID() uint64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PostParams) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostParams) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type PostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArrMessage []*PostParams `protobuf:"bytes,1,rep,name=ArrMessage,proto3" json:"ArrMessage,omitempty"`
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_raw_protos_post_protos_post_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_raw_protos_post_protos_post_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_grpc_raw_protos_post_protos_post_proto_rawDescGZIP(), []int{1}
}

func (x *PostResponse) GetArrMessage() []*PostParams {
	if x != nil {
		return x.ArrMessage
	}
	return nil
}

var File_grpc_raw_protos_post_protos_post_proto protoreflect.FileDescriptor

var file_grpc_raw_protos_post_protos_post_proto_rawDesc = []byte{
	0x0a, 0x26, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x72, 0x61, 0x77, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6f,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x5e, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x42, 0x6f,
	0x64, 0x79, 0x22, 0x47, 0x0a, 0x0c, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x41, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52,
	0x0a, 0x41, 0x72, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x54, 0x0a, 0x0b, 0x50,
	0x6f, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x69, 0x47, 0x52, 0x50, 0x43, 0x12, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x1a, 0x19, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_raw_protos_post_protos_post_proto_rawDescOnce sync.Once
	file_grpc_raw_protos_post_protos_post_proto_rawDescData = file_grpc_raw_protos_post_protos_post_proto_rawDesc
)

func file_grpc_raw_protos_post_protos_post_proto_rawDescGZIP() []byte {
	file_grpc_raw_protos_post_protos_post_proto_rawDescOnce.Do(func() {
		file_grpc_raw_protos_post_protos_post_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_raw_protos_post_protos_post_proto_rawDescData)
	})
	return file_grpc_raw_protos_post_protos_post_proto_rawDescData
}

var file_grpc_raw_protos_post_protos_post_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grpc_raw_protos_post_protos_post_proto_goTypes = []interface{}{
	(*PostParams)(nil),   // 0: post_protos.PostParams
	(*PostResponse)(nil), // 1: post_protos.PostResponse
	(*empty.Empty)(nil),  // 2: google.protobuf.Empty
}
var file_grpc_raw_protos_post_protos_post_proto_depIdxs = []int32{
	0, // 0: post_protos.PostResponse.ArrMessage:type_name -> post_protos.PostParams
	2, // 1: post_protos.PostService.GetOpenApiGRPC:input_type -> google.protobuf.Empty
	1, // 2: post_protos.PostService.GetOpenApiGRPC:output_type -> post_protos.PostResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_raw_protos_post_protos_post_proto_init() }
func file_grpc_raw_protos_post_protos_post_proto_init() {
	if File_grpc_raw_protos_post_protos_post_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_raw_protos_post_protos_post_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_raw_protos_post_protos_post_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_raw_protos_post_protos_post_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_raw_protos_post_protos_post_proto_goTypes,
		DependencyIndexes: file_grpc_raw_protos_post_protos_post_proto_depIdxs,
		MessageInfos:      file_grpc_raw_protos_post_protos_post_proto_msgTypes,
	}.Build()
	File_grpc_raw_protos_post_protos_post_proto = out.File
	file_grpc_raw_protos_post_protos_post_proto_rawDesc = nil
	file_grpc_raw_protos_post_protos_post_proto_goTypes = nil
	file_grpc_raw_protos_post_protos_post_proto_depIdxs = nil
}
